[env]
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    jgromes/RadioLib
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

; ============================================================
; LEVEL 1: Базовий зв'язок LoRa
; ============================================================
[env:tx-lvl1]
build_src_filter = +<transmitter/lvl1.cpp>
upload_port = COM4
monitor_port = COM4

[env:rx-lvl1]
build_src_filter = +<receiver/lvl1.cpp>
upload_port = COM5
monitor_port = COM5

; ============================================================
; LEVEL 2: Тестування швидкості LoRa (SF / BW)
; ============================================================
[env:tx-lvl2]
build_src_filter = +<transmitter/lvl2.cpp>
upload_port = COM4
monitor_port = COM4

[env:rx-lvl2]
build_src_filter = +<receiver/lvl2.cpp>
upload_port = COM5
monitor_port = COM5

; ============================================================
; LEVEL 3: Модуляція FSK
; ============================================================
[env:tx-lvl3-fsk]
build_src_filter = +<transmitter/lvl3.cpp>
upload_port = COM4
monitor_port = COM4

[env:rx-lvl3-fsk]
build_src_filter = +<receiver/lvl3.cpp>
upload_port = COM5
monitor_port = COM5

; ============================================================
; FreeRTOS Queue & Tasks
; ============================================================
[env:rtos-radio]
build_src_filter = +<rtos-radio/main.cpp>
upload_port = COM4
monitor_port = COM4